[package]
name = "AnimaWeave"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
insta = "1.43.1"
tempfile = "3.20.0"
